version: '3.8'

x-app: &app
  build:
    args:
      RUBY_VERSION: 3.0.2
    context: .
  depends_on:
    - db
    - redis
  stdin_open: true
  tty: true
  volumes:
    - .:/app:cached
    - bundle:/usr/local/bundle

services:
  db:
    environment:
      POSTGRES_PASSWORD: postgres
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    restart: always

  web:
    <<: *app
    command: rails s -b 0.0.0.0
    ports:
      - '3000:3000'

  # cable:
  #   <<: *app
  #   command: puma -p 28080 cable/config.ru
  #   ports:
  #     - '28080:28080'

volumes:
  bundle:
  op-connect-data:
  postgres:
