x-app:
  &app
  build:
    args:
      UID: 1000
      GID: 1000
      RAILS_ENV: development
    context: .
    target: build
  depends_on:
    - db
    - redis
  environment:
    DATABASE_URL: postgres://postgres:postgres@db:5432/listo_development
  restart: unless-stopped
  stdin_open: true
  stop_grace_period: "3s"
  tty: true
  volumes:
    - .:/srv:cached
    - bundle:/usr/local/bundle
    - type: tmpfs
      target: /srv/app/tmp/pids/

services:
  chrome-server:
    image: selenium/standalone-chrome:latest
    platform: linux/amd64
    ports:
      - "7900:7900"

  firefox-server:
    image: selenium/standalone-firefox:latest
    platform: linux/amd64
    ports:
      - "7901:7900"

  db:
    environment:
      POSTGRES_PASSWORD: postgres
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    restart: always

  web:
    <<: *app
    command: rails s -b 0.0.0.0
    ports:
      - '3000:3000'
  # cable:
  #   <<: *app
  #   command: puma -p 28080 cable/config.ru
  #   ports:
  #     - '28080:28080'

volumes:
  bundle:
  postgres:
