default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV.fetch("POSTGRES_DB") { "app" } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "postgres" } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "db" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "app" } %>_development

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "app" } %>_test

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "app" } %>_production
